### ISSUE TITLE
Feature Add - Custom Style To Text Options

### ISSUE THREAD

**Issue by crh3675** [marcj/jquery-selectBox#78]
I needed custom style to the text elements of my selectboxes.  In order to do that, I needed to separate parts of the text with a delimiter and tell selectBox how to deal with them.  This code, enhances selectBox by creating HTML options that can have custom styles for parts of the option text.  

``` javascript
// allows us to have markup in options
$.fn.proxyBox = jQuery.fn.selectBox;

$.fn.selectBox = function()
{
   var f = function()
   {
      $('span.selectBox-label, ul.selectBox-options li a').each(function(){
         var txt = $(this).text();
         if(txt.match(/\|/))
         {
            var parts = txt.split('|');
            var html = parts.map(function(item,index){ return '<span class="selectBox-p'+index+'">'+item+'</span>' }).join('');

            $(this).html(html);
         }
      });
   }

   var a = arguments;
   $(this).each(function(){
      $(this).proxyBox.apply(this, a);
      $(this).bind('change', f);
      f();
   });
}
```

You can then style text elements using the class name **selectBox-p[n]** where **n** represent the position.

Preview image:

http://awesomescreenshot.com/0c63sw1ca

CSS Style Used:

``` css
.selectBox-p0{
   font-weight:bold;
   font-style:normal;
   color:#3A3E41;
   border-right:1px dotted #666;
   padding-right:5px;
   margin-right:5px;
}
```
